---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
  labels:
    app: equinix
  name: equinix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equinix
  template:
    metadata:
      annotations:
        restart-version: "6"
      labels:
        app: equinix
        run: equinix
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: docker.io/pegatim/equinix-nodejs:21.7.1
        imagePullPolicy: Always
        name: equinix-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /nodejs/template-nodejs-v1/config
          name: equinix-config
          readOnly: true
      securityContext: {}
      volumes:
      - name: equinix-config
        secret:
          defaultMode: 420
          secretName: equinix-config
